import Layout from '@/components/shared/Layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertTriangle, Heart, Phone } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Link } from 'react-router-dom';

const MedicalDisclaimer = () => {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Card>
          <CardHeader className="text-center space-y-2">
            <div className="mx-auto h-12 w-12 rounded-full bg-destructive/10 flex items-center justify-center mb-2">
              <AlertTriangle className="h-6 w-6 text-destructive" />
            </div>
            <CardTitle className="text-3xl">Medical &amp; Emergency Disclaimer</CardTitle>
            <p className="text-muted-foreground text-sm">
              Last updated: February 12, 2026 &bull; Version 1.0.0
            </p>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none space-y-6">
            <Alert className="border-destructive/50 bg-destructive/5">
              <AlertTriangle className="h-5 w-5 text-destructive" />
              <AlertDescription className="text-destructive font-semibold text-base">
                IN A LIFE-THREATENING EMERGENCY, CALL 999 (Kenya) OR YOUR LOCAL EMERGENCY NUMBER IMMEDIATELY. 
                DO NOT RELY SOLELY ON THIS PLATFORM.
              </AlertDescription>
            </Alert>

            <section>
              <h2 className="text-xl font-semibold mt-6 mb-3">1. Not a Medical Device</h2>
              <p>
                UhaiLink is an <strong>information storage and communication platform</strong>. It is 
                <strong> NOT</strong> a medical device, diagnostic system, treatment tool, or substitute 
                for professional medical care as defined by the Kenya Pharmacy and Poisons Board, 
                the Kenya Medical Practitioners and Dentists Council, or any regulatory authority.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-6 mb-3">2. AI First Aid Assistant</h2>
              <div className="bg-yellow-50 dark:bg-yellow-950/20 border border-yellow-200 dark:border-yellow-900 rounded-lg p-4 my-4">
                <p className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">AI Guidance Limitations</p>
                <ul className="list-disc pl-6 space-y-2 text-yellow-900 dark:text-yellow-100">
                  <li>
                    The AI first aid assistant (Uhai Assist) provides <strong>general first aid guidance only</strong>.
                  </li>
                  <li>
                    AI responses are generated by third-party AI language models and may contain 
                    <strong> errors, inaccuracies, or outdated information</strong>.
                  </li>
                  <li>
                    AI guidance does <strong>NOT</strong> constitute medical advice, diagnosis, or treatment.
                  </li>
                  <li>
                    Never delay seeking professional medical help based on AI-generated guidance.
                  </li>
                  <li>
                    The AI does not have access to your complete medical history, physical examination 
                    findings, or laboratory results.
                  </li>
                  <li>
                    AI responses should be verified by qualified healthcare professionals.
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-6 mb-3">3. Emergency SOS System</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  The Emergency SOS feature sends SMS notifications to your designated emergency 
                  contacts. It does <strong>NOT</strong> directly contact emergency services (police, 
                  ambulance, fire brigade).
                </li>
                <li>
                  SMS delivery depends on mobile network availability, recipient phone status, 
                  and third-party SMS providers. <strong>Delivery is not guaranteed.</strong>
                </li>
                <li>
                  Location data shared during emergencies is based on your device&apos;s GPS and 
                  may not be accurate in all environments.
                </li>
                <li>
                  Always call <strong>999</strong> or your local emergency number directly in 
                  addition to using the SOS feature.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-6 mb-3">4. QR Code Medical Profiles</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  QR code profiles provide medical information to anyone who scans the code. 
                  You are responsible for who has physical access to your QR code.
                </li>
                <li>
                  UhaiLink cannot guarantee that emergency responders will scan or act upon 
                  your QR code during an emergency.
                </li>
                <li>
                  The accuracy of displayed medical information depends entirely on what you 
                  have entered in your profile. <strong>Keep your profile updated.</strong>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-6 mb-3">5. Your Responsibility</h2>
              <p>
                You acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You are solely responsible for the accuracy of your medical information</li>
                <li>You will not rely on UhaiLink as your only means of emergency communication</li>
                <li>You will keep your medical profile accurate and current</li>
                <li>You will seek professional medical advice for health concerns</li>
                <li>
                  You understand that technology may fail during emergencies and have backup 
                  plans in place (physical medical ID, written emergency information)
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-6 mb-3">6. Emergency Contact Numbers — Kenya</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
                <div className="flex items-center gap-3 p-3 bg-destructive/5 rounded-lg border border-destructive/20">
                  <Phone className="h-5 w-5 text-destructive" />
                  <div>
                    <p className="font-semibold">Emergency Services</p>
                    <p className="text-lg font-bold text-destructive">999</p>
                  </div>
                </div>
                <div className="flex items-center gap-3 p-3 bg-destructive/5 rounded-lg border border-destructive/20">
                  <Phone className="h-5 w-5 text-destructive" />
                  <div>
                    <p className="font-semibold">Kenya Red Cross</p>
                    <p className="text-lg font-bold text-destructive">1199</p>
                  </div>
                </div>
                <div className="flex items-center gap-3 p-3 bg-destructive/5 rounded-lg border border-destructive/20">
                  <Heart className="h-5 w-5 text-destructive" />
                  <div>
                    <p className="font-semibold">St. John Ambulance</p>
                    <p className="text-lg font-bold text-destructive">+254 722 208 208</p>
                  </div>
                </div>
                <div className="flex items-center gap-3 p-3 bg-destructive/5 rounded-lg border border-destructive/20">
                  <Phone className="h-5 w-5 text-destructive" />
                  <div>
                    <p className="font-semibold">Police</p>
                    <p className="text-lg font-bold text-destructive">999 / 112</p>
                  </div>
                </div>
              </div>
            </section>

            <section className="mt-8 pt-6 border-t">
              <p className="text-sm text-muted-foreground">
                By using UhaiLink, you acknowledge that you have read, understood, and agree to 
                this Medical &amp; Emergency Disclaimer. For questions, contact us at{' '}
                <strong>support@uhailink.com</strong>. See also our{' '}
                <Link to="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link> and{' '}
                <Link to="/terms-of-service" className="text-primary hover:underline">Terms of Service</Link>.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
};

export default MedicalDisclaimer;
